// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/amitshekhariitbhu/go-backend-clean-architecture/domain"
	mock "github.com/stretchr/testify/mock"
)

// PollAdminUsecase is an autogenerated mock type for the PollAdminUsecase type
type PollAdminUsecase struct {
	mock.Mock
}

// CreatePoll provides a mock function with given fields: c, poll
func (_m *PollAdminUsecase) CreatePoll(c context.Context, poll *domain.Poll) error {
	ret := _m.Called(c, poll)

	if len(ret) == 0 {
		panic("no return value specified for CreatePoll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Poll) error); ok {
		r0 = rf(c, poll)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, id
func (_m *PollAdminUsecase) Delete(c context.Context, id string) error {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditPoll provides a mock function with given fields: c, poll
func (_m *PollAdminUsecase) EditPoll(c context.Context, poll *domain.Poll) error {
	ret := _m.Called(c, poll)

	if len(ret) == 0 {
		panic("no return value specified for EditPoll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Poll) error); ok {
		r0 = rf(c, poll)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBySheetID provides a mock function with given fields: c, sheetID
func (_m *PollAdminUsecase) GetBySheetID(c context.Context, sheetID string) ([]domain.Poll, error) {
	ret := _m.Called(c, sheetID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySheetID")
	}

	var r0 []domain.Poll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Poll, error)); ok {
		return rf(c, sheetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Poll); ok {
		r0 = rf(c, sheetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Poll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, sheetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPollAdminUsecase creates a new instance of PollAdminUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPollAdminUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PollAdminUsecase {
	mock := &PollAdminUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
