// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/amitshekhariitbhu/go-backend-clean-architecture/domain"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	time "time"
)

// SheetRepository is an autogenerated mock type for the SheetRepository type
type SheetRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sheet
func (_m *SheetRepository) Create(ctx context.Context, sheet domain.Sheet) error {
	ret := _m.Called(ctx, sheet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Sheet) error); ok {
		r0 = rf(ctx, sheet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SheetRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, pagination
func (_m *SheetRepository) GetAll(ctx context.Context, pagination domain.PaginationQuery) ([]domain.Sheet, int64, error) {

	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {

		panic("no return value specified for GetAll")

	}

	var r0 []domain.Sheet

	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.Sheet); ok {

		r0 = rf(ctx, pagination)

	} else {

		if ret.Get(0) != nil {

			r0 = ret.Get(0).([]domain.Sheet)

		}

	}

	var r1 int64

	if len(ret) > 1 {

		if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) int64); ok {

			r1 = rf(ctx, pagination)

		} else if ret.Get(1) != nil {

			r1 = ret.Get(1).(int64)

		}

	}

	var r2 error

	if len(ret) > 2 {

		if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {

			r2 = rf(ctx, pagination)

		} else {

			r2 = ret.Error(2)

		}

	}

	return r0, r1, r2

}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *SheetRepository) GetByUserID(ctx context.Context, userID string, pagination domain.PaginationQuery) ([]domain.Sheet, int64, error) {

	ret := _m.Called(ctx, userID, pagination)

	if len(ret) == 0 {

		panic("no return value specified for GetByUserID")

	}

	var r0 []domain.Sheet

	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaginationQuery) []domain.Sheet); ok {

		r0 = rf(ctx, userID, pagination)

	} else {

		if ret.Get(0) != nil {

			r0 = ret.Get(0).([]domain.Sheet)

		}

	}

	var r1 int64

	if len(ret) > 1 {

		if rf, ok := ret.Get(1).(func(context.Context, string, domain.PaginationQuery) int64); ok {

			r1 = rf(ctx, userID, pagination)

		} else if ret.Get(1) != nil {

			r1 = ret.Get(1).(int64)

		}

	}

	var r2 error

	if len(ret) > 2 {

		if rf, ok := ret.Get(2).(func(context.Context, string, domain.PaginationQuery) error); ok {

			r2 = rf(ctx, userID, pagination)

		} else {

			r2 = ret.Error(2)

		}

	}

	return r0, r1, r2

}

// UpdateStatus provides a mock function with given fields: ctx, id, status, approvedBy, approvedAt
func (_m *SheetRepository) UpdateStatus(ctx context.Context, id string, status domain.SheetStatus, approvedBy primitive.ObjectID, approvedAt time.Time) error {
	ret := _m.Called(ctx, id, status, approvedBy, approvedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SheetStatus, primitive.ObjectID, time.Time) error); ok {
		r0 = rf(ctx, id, status, approvedBy, approvedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSheetRepository creates a new instance of SheetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSheetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SheetRepository {
	mock := &SheetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
